version: "3"


services:
    postgres:
        image: postgres:13
        ports:
            - 5429:5432
        environment:
            - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
            - POSTGRES_USER=${POSTGRES_USER}
            - POSTGRES_DB=${POSTGRES_DB}

        env_file: .env
        volumes:
            - career_postgres_data:/var/lib/postgresql/data

    bot:
        build: .
        depends_on:
            - postgres
        env_file: .env


volumes:
    career_postgres_data:
        external: true